name: check copyright
description: 

branding:
  icon: zap
  color: gray-dark
  
runs:
  using: "composite"
  steps:
    - run: python3 -m pip install -qqq --upgrade pip
      shell: bash
    - run: python3 -m pip install -qqq PyGithub
      shell: bash
    - run: |
        echo " --- CHECKING COPYRIGHT --- "
        output=$GITHUB_ACTION_PATH/src/check-copyright.py
        output="${output//'%'/'%25'}"
        output="${output//$'\n'/'%0A'}"
        output="${output//$'\r'/'%0D'}" 
        echo "::set-output name=changelog::$output"
      shell: bash
      id: step1
    - name: Print changelog
        run: |
        echo "${{ steps.step1.outputs.changelog }}"
